/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyVaccination;
/**
 *
 * @author leebe
 */
public class Personnel_Home extends javax.swing.JFrame {

    /**
     * Creates new form Personnel_Home
     */
    public Personnel_Home() {
        initComponents();
//        ImageIcon img = new ImageIcon("src/MyVaccination/Images/Original Logo - Copy.png");
//        this.setIconImage(img.getImage());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMngVC = new javax.swing.JButton();
        btnMngUser = new javax.swing.JButton();
        btnMngApt = new javax.swing.JButton();
        btnMngSupply = new javax.swing.JButton();
        homePersonnelHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));

        btnMngVC.setBackground(new java.awt.Color(204, 153, 255));
        btnMngVC.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnMngVC.setForeground(new java.awt.Color(0, 0, 0));
        btnMngVC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/Vaccination_Centre_32.png"))); // NOI18N
        btnMngVC.setText("Manage Vaccination Centres");
        btnMngVC.setAlignmentY(0.0F);
        btnMngVC.setIconTextGap(20);
        btnMngVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngVCActionPerformed(evt);
            }
        });

        btnMngUser.setBackground(new java.awt.Color(204, 153, 255));
        btnMngUser.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnMngUser.setForeground(new java.awt.Color(0, 0, 0));
        btnMngUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/User.png"))); // NOI18N
        btnMngUser.setText("Manage Users");
        btnMngUser.setAlignmentY(0.0F);
        btnMngUser.setIconTextGap(20);
        btnMngUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngUserActionPerformed(evt);
            }
        });

        btnMngApt.setBackground(new java.awt.Color(204, 153, 255));
        btnMngApt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnMngApt.setForeground(new java.awt.Color(0, 0, 0));
        btnMngApt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/Appointment2_48.png"))); // NOI18N
        btnMngApt.setText("Manage Appointments");
        btnMngApt.setAlignmentY(0.0F);
        btnMngApt.setIconTextGap(20);
        btnMngApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngAptActionPerformed(evt);
            }
        });

        btnMngSupply.setBackground(new java.awt.Color(204, 153, 255));
        btnMngSupply.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnMngSupply.setForeground(new java.awt.Color(0, 0, 0));
        btnMngSupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/Vaccine.png"))); // NOI18N
        btnMngSupply.setText("Manage Vaccine Supply");
        btnMngSupply.setAlignmentY(0.0F);
        btnMngSupply.setIconTextGap(20);
        btnMngSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngSupplyActionPerformed(evt);
            }
        });

        homePersonnelHeader.setBackground(new java.awt.Color(204, 153, 255));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Logo_200.png"))); // NOI18N

        javax.swing.GroupLayout homePersonnelHeaderLayout = new javax.swing.GroupLayout(homePersonnelHeader);
        homePersonnelHeader.setLayout(homePersonnelHeaderLayout);
        homePersonnelHeaderLayout.setHorizontalGroup(
            homePersonnelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePersonnelHeaderLayout.createSequentialGroup()
                .addComponent(lblLogo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homePersonnelHeaderLayout.setVerticalGroup(
            homePersonnelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePersonnelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngApt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(btnMngUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngSupply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngVC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMngApt, btnMngSupply, btnMngUser, btnMngVC});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homePersonnelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngUser, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngVC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngSupply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngApt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMngApt, btnMngSupply, btnMngUser, btnMngVC});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngVCActionPerformed
            Personnel_ManageVaccinationCentre vc = new Personnel_ManageVaccinationCentre();
            vc.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnMngVCActionPerformed

    private void btnMngUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngUserActionPerformed
        Personnel_ManageUsers mngUser = new Personnel_ManageUsers();
        mngUser.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMngUserActionPerformed

    private void btnMngAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngAptActionPerformed
        // Redirect to Manage Appointment
        Personnel_ManageAppointment apt = new Personnel_ManageAppointment();
        apt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMngAptActionPerformed

    private void btnMngSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngSupplyActionPerformed
        // Navigate to manage Vaccine supply
         Personnel_ManageVaccineSupply mngForm = new Personnel_ManageVaccineSupply();
        mngForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMngSupplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personnel_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personnel_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personnel_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personnel_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personnel_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngApt;
    private javax.swing.JButton btnMngSupply;
    private javax.swing.JButton btnMngUser;
    private javax.swing.JButton btnMngVC;
    private javax.swing.JPanel homePersonnelHeader;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
