/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyVaccination;

import Helper_Classes.LGoodTimePicker_TimeVeto;
import MyVaccination.Classes.Vaccination_Centre;
import com.github.lgooddatepicker.components.TimePicker;
import com.github.lgooddatepicker.components.TimePickerSettings;
import java.awt.TrayIcon;
import java.time.LocalTime;
import javax.swing.JOptionPane;

/**
 *
 * @author leebe
 */
public class Personnel_VaccinationCentreForm extends javax.swing.JFrame {

    /**
     * Creates new form Personnel_VaccinationCentreForm
     */
    String id = "";

    public Personnel_VaccinationCentreForm() {
        initComponents();
    }

    //For edit mode
    public Personnel_VaccinationCentreForm(String id) {
        this.id = id;
        initComponents();

        Vaccination_Centre vc = Vaccination_Centre.getCentre(id);
        txtVcName.setText(vc.getName());
        dtVcOpeningTime.setTime(vc.getOpeningTime());
        dtVcClosingTime.setTime(vc.getClosingTime());

        if (vc.getStatus().equals("Active")) {
            cmbVcStatus.setSelectedIndex(0);
        } else {
            cmbVcStatus.setSelectedIndex(1);
        }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePersonnelHeader = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnVcSave = new javax.swing.JButton();
        btnVcCancel = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        cmbVcStatus = new javax.swing.JComboBox<>();
        txtVcName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dtVcClosingTime = new com.github.lgooddatepicker.components.TimePicker();
        jLabel1 = new javax.swing.JLabel();
        TimePickerSettings dtVcOpenTimeSettings = new TimePickerSettings();
        dtVcOpeningTime = new com.github.lgooddatepicker.components.TimePicker(dtVcOpenTimeSettings);
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vaccination Centre");
        setName("frmVc"); // NOI18N
        setSize(getPreferredSize());

        homePersonnelHeader.setBackground(new java.awt.Color(204, 153, 255));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Logo_200.png"))); // NOI18N
        btnHome.setBackground(new java.awt.Color(204, 153, 255));
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setFocusPainted(false);
        btnHome.setFocusable(false);
        btnHome.setRequestFocusEnabled(false);
        btnHome.setRolloverEnabled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePersonnelHeaderLayout = new javax.swing.GroupLayout(homePersonnelHeader);
        homePersonnelHeader.setLayout(homePersonnelHeaderLayout);
        homePersonnelHeaderLayout.setHorizontalGroup(
            homePersonnelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePersonnelHeaderLayout.createSequentialGroup()
                .addComponent(btnHome)
                .addGap(0, 745, Short.MAX_VALUE))
        );
        homePersonnelHeaderLayout.setVerticalGroup(
            homePersonnelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePersonnelHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHome))
        );

        btnVcSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/Save.png"))); // NOI18N
        btnVcSave.setText("Save");
        btnVcSave.setBackground(new java.awt.Color(0, 204, 51));
        btnVcSave.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnVcSave.setForeground(new java.awt.Color(0, 0, 0));
        btnVcSave.setIconTextGap(10);
        btnVcSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVcSaveActionPerformed(evt);
            }
        });

        btnVcCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/Cancel.png"))); // NOI18N
        btnVcCancel.setText("Cancel");
        btnVcCancel.setBackground(new java.awt.Color(204, 51, 0));
        btnVcCancel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnVcCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnVcCancel.setIconTextGap(10);
        btnVcCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVcCancelActionPerformed(evt);
            }
        });

        cmbVcStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        cmbVcStatus.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtVcName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel2.setLabelFor(dtVcOpeningTime);
        jLabel2.setText("Opening Time :");
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel3.setLabelFor(dtVcClosingTime);
        jLabel3.setText("Closing Time :");
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel4.setLabelFor(dtVcClosingTime);
        jLabel4.setText("Status :");
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        dtVcClosingTime.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel1.setLabelFor(txtVcName);
        jLabel1.setText("Vaccination Centre Name :");
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        dtVcOpenTimeSettings.setVetoPolicy(new LGoodTimePicker_TimeVeto());
        dtVcOpeningTime.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLayeredPane1.setLayer(cmbVcStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtVcName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(dtVcClosingTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(dtVcOpeningTime, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbVcStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, 207, Short.MAX_VALUE)
                    .addComponent(dtVcOpeningTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtVcName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtVcClosingTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbVcStatus, dtVcClosingTime});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVcName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtVcOpeningTime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtVcClosingTime, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVcStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Main Details", jLayeredPane1);
        jTabbedPane1.addTab("Location", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePersonnelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVcCancel)
                        .addGap(36, 36, 36)
                        .addComponent(btnVcSave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homePersonnelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVcSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVcCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Personnel_Home home = new Personnel_Home();
        home.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnVcSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVcSaveActionPerformed
        boolean success;
        String message = "";

        if (id != "") {
            //Edit
            success = Vaccination_Centre.updateCentre(id, txtVcName.getText(), dtVcOpeningTime.getTime(), dtVcClosingTime.getTime(), cmbVcStatus.getItemAt(cmbVcStatus.getSelectedIndex()));
            message = "Failed to update record for "+ txtVcName.getText() +"!";
        } else {
            //New
            success = Vaccination_Centre.registerCentre(txtVcName.getText(), dtVcOpeningTime.getTime(), dtVcClosingTime.getTime(), cmbVcStatus.getItemAt(cmbVcStatus.getSelectedIndex()));
            message = "Failed to register new vaccination centre!";
        }

        //Verify success of registration
        if (!success) {
            JOptionPane.showMessageDialog(this, message, "Vaccination Centre", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Personnel_ManageVaccinationCentre vcHome = new Personnel_ManageVaccinationCentre();
        vcHome.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnVcSaveActionPerformed

    private void btnVcCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVcCancelActionPerformed

        //Check if user is certain
        JOptionPane.showConfirmDialog(this, "Warning, no unsaved changes will be saved!", "Cancel Vaccination Centre Registration", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        // Return to Manage Vaccination Centre page
        this.setVisible(false);
        this.dispose();
        Personnel_ManageVaccinationCentre vc = new Personnel_ManageVaccinationCentre();
        vc.setVisible(true);
    }//GEN-LAST:event_btnVcCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personnel_VaccinationCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personnel_VaccinationCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personnel_VaccinationCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personnel_VaccinationCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personnel_VaccinationCentreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnVcCancel;
    private javax.swing.JButton btnVcSave;
    private javax.swing.JComboBox<String> cmbVcStatus;
    private com.github.lgooddatepicker.components.TimePicker dtVcClosingTime;
    private com.github.lgooddatepicker.components.TimePicker dtVcOpeningTime;
    private javax.swing.JPanel homePersonnelHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtVcName;
    // End of variables declaration//GEN-END:variables
}
