/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyVaccination;

import MyVaccination.Helper_Classes.LGoodTimePicker_TimeVeto;
import MyVaccination.Classes.Vaccination_Centre;
import MyVaccination.Classes.Location;
import MyVaccination.Classes.Personnel;
import MyVaccination.Classes.Stock;
import MyVaccination.Classes.Vaccine;
import com.github.lgooddatepicker.components.TimePickerSettings;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author leebe
 */
public class Personnel_VaccinationCentreForm extends javax.swing.JFrame {

    /**
     * Creates new form Personnel_VaccinationCentreForm
     */
    String id = "";
    String userId = "";
    Vaccination_Centre vc;

    public Personnel_VaccinationCentreForm() {
        initComponents();
        vc = new Vaccination_Centre();
        ImageIcon img = new ImageIcon("src/MyVaccination/Images/Logo_Background1024.jpg");
        this.setIconImage(img.getImage());

        lblViewProfile.setVisible(false);
        lblLogout.setVisible(false);
    }

    public Personnel_VaccinationCentreForm(String userId) {
        initComponents();
        vc = new Vaccination_Centre();

        this.userId = userId;
        ImageIcon img = new ImageIcon("src/MyVaccination/Images/Logo_Background1024.jpg");
        this.setIconImage(img.getImage());

        Personnel user = Personnel.getPersonnel(userId);

        lblUsername.setText(user.getUsername());

        lblViewProfile.setVisible(false);
        lblLogout.setVisible(false);
    }

    //For edit mode
    public Personnel_VaccinationCentreForm(String id, String userId) {
        this.id = id;
        initComponents();

        vc = Vaccination_Centre.getCentre(id);
        txtVcName.setText(vc.getName());
        dtVcOpeningTime.setTime(vc.getOpeningTime());
        dtVcClosingTime.setTime(vc.getClosingTime());
        spinVcCapacity.setValue(vc.getCapacity());

        if (vc.getStatus().equals("Active")) {
            cmbVcStatus.setSelectedIndex(0);
        } else {
            cmbVcStatus.setSelectedIndex(1);
        }

        //Location
        txtVcAddr1.setText(vc.getLocation().getAddress1());
        txtVcAddr2.setText(vc.getLocation().getAddress2());
        List<String> stateList = Arrays.asList(Location.getStateList());
        cmbVcState.setSelectedIndex(stateList.indexOf(vc.getLocation().getState()));

        this.userId = userId;
        ImageIcon img = new ImageIcon("src/MyVaccination/Images/Logo_Background1024.jpg");
        this.setIconImage(img.getImage());

        Personnel user = Personnel.getPersonnel(userId);

        lblUsername.setText(user.getUsername());

        lblViewProfile.setVisible(false);
        lblLogout.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaResupply = new javax.swing.JDialog();
        btnResupplyCancel = new javax.swing.JButton();
        btnResupplySave = new javax.swing.JButton();
        cmbResupplyVaccine =  new javax.swing.JComboBox<>(Vaccine.getListOfVaccines());
        spinResupply = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        homePersonnelHeader = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        btnVcSave = new javax.swing.JButton();
        btnVcCancel = new javax.swing.JButton();
        panelTabbedVc = new javax.swing.JTabbedPane();
        panelMainDetails = new javax.swing.JLayeredPane();
        cmbVcStatus = new javax.swing.JComboBox<>();
        txtVcName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TimePickerSettings dtVcCloseTimeSettings = new TimePickerSettings();
        dtVcClosingTime = new com.github.lgooddatepicker.components.TimePicker(dtVcCloseTimeSettings);
        dtVcCloseTimeSettings.setVetoPolicy(new LGoodTimePicker_TimeVeto());
        jLabel1 = new javax.swing.JLabel();
        TimePickerSettings dtVcOpenTimeSettings = new TimePickerSettings();
        dtVcOpeningTime = new com.github.lgooddatepicker.components.TimePicker(dtVcOpenTimeSettings);
        jLabel10 = new javax.swing.JLabel();
        spinVcCapacity = new javax.swing.JSpinner();
        panelLocation = new javax.swing.JLayeredPane();
        cmbVcState = cmbVcState = new javax.swing.JComboBox<>(Location.getStateList());
        txtVcAddr1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtVcAddr2 = new javax.swing.JTextField();
        panelSupply = new javax.swing.JPanel();
        panelVaccineChart = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVcSupply = new javax.swing.JTable();
        btnVcSupply = new javax.swing.JButton();
        lblViewProfile = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();

        diaResupply.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        diaResupply.setMinimumSize(new java.awt.Dimension(403, 288));

        btnResupplyCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/Cancel.png"))); // NOI18N
        btnResupplyCancel.setText("Cancel");
        btnResupplyCancel.setBackground(new java.awt.Color(204, 51, 0));
        btnResupplyCancel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnResupplyCancel.setIconTextGap(10);
        btnResupplyCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResupplyCancelActionPerformed(evt);
            }
        });

        btnResupplySave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/Save.png"))); // NOI18N
        btnResupplySave.setText("Confirm");
        btnResupplySave.setBackground(new java.awt.Color(0, 204, 51));
        btnResupplySave.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnResupplySave.setIconTextGap(10);
        btnResupplySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResupplySaveActionPerformed(evt);
            }
        });

        cmbResupplyVaccine.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        spinResupply.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinResupply.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel5.setText("Vaccine Brand");
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel7.setText("Amount");
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout diaResupplyLayout = new javax.swing.GroupLayout(diaResupply.getContentPane());
        diaResupply.getContentPane().setLayout(diaResupplyLayout);
        diaResupplyLayout.setHorizontalGroup(
            diaResupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaResupplyLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(diaResupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(diaResupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(spinResupply, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbResupplyVaccine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(diaResupplyLayout.createSequentialGroup()
                        .addComponent(btnResupplyCancel)
                        .addGap(36, 36, 36)
                        .addComponent(btnResupplySave))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        diaResupplyLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbResupplyVaccine, spinResupply});

        diaResupplyLayout.setVerticalGroup(
            diaResupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaResupplyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbResupplyVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinResupply, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(diaResupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResupplySave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResupplyCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        diaResupplyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbResupplyVaccine, spinResupply});

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyVaccination");
        setMinimumSize(new java.awt.Dimension(950, 520));
        setName("frmVc"); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 520));
        setSize(getPreferredSize());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePersonnelHeader.setBackground(new java.awt.Color(204, 153, 255));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Logo_200.png"))); // NOI18N
        btnHome.setBackground(new java.awt.Color(204, 153, 255));
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setFocusPainted(false);
        btnHome.setFocusable(false);
        btnHome.setRequestFocusEnabled(false);
        btnHome.setRolloverEnabled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lblUsername.setText("User Name");
        lblUsername.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsernameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUsernameMousePressed(evt);
            }
        });

        javax.swing.GroupLayout homePersonnelHeaderLayout = new javax.swing.GroupLayout(homePersonnelHeader);
        homePersonnelHeader.setLayout(homePersonnelHeaderLayout);
        homePersonnelHeaderLayout.setHorizontalGroup(
            homePersonnelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePersonnelHeaderLayout.createSequentialGroup()
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 628, Short.MAX_VALUE)
                .addComponent(lblUsername)
                .addGap(32, 32, 32))
        );
        homePersonnelHeaderLayout.setVerticalGroup(
            homePersonnelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePersonnelHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHome))
            .addGroup(homePersonnelHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(homePersonnelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        btnVcSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/Save.png"))); // NOI18N
        btnVcSave.setText("Save");
        btnVcSave.setBackground(new java.awt.Color(0, 204, 51));
        btnVcSave.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnVcSave.setHideActionText(true);
        btnVcSave.setIconTextGap(10);
        btnVcSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVcSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnVcSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 105, 39));

        btnVcCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/Cancel.png"))); // NOI18N
        btnVcCancel.setText("Cancel");
        btnVcCancel.setBackground(new java.awt.Color(204, 51, 0));
        btnVcCancel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnVcCancel.setHideActionText(true);
        btnVcCancel.setIconTextGap(10);
        btnVcCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVcCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnVcCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, 39));

        cmbVcStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        cmbVcStatus.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtVcName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel2.setLabelFor(dtVcOpeningTime);
        jLabel2.setText("Opening Time :");
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel3.setLabelFor(dtVcClosingTime);
        jLabel3.setText("Closing Time :");
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel4.setLabelFor(dtVcClosingTime);
        jLabel4.setText("Status :");
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        dtVcClosingTime.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel1.setLabelFor(txtVcName);
        jLabel1.setText("Vaccination Centre Name :");
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        dtVcOpenTimeSettings.setVetoPolicy(new LGoodTimePicker_TimeVeto());
        dtVcOpeningTime.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel10.setLabelFor(dtVcClosingTime);
        jLabel10.setText("Capacity :");
        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        spinVcCapacity.setModel(new javax.swing.SpinnerNumberModel(10, 10, null, 5));

        panelMainDetails.setLayer(cmbVcStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMainDetails.setLayer(txtVcName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMainDetails.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMainDetails.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMainDetails.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMainDetails.setLayer(dtVcClosingTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMainDetails.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMainDetails.setLayer(dtVcOpeningTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMainDetails.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMainDetails.setLayer(spinVcCapacity, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelMainDetailsLayout = new javax.swing.GroupLayout(panelMainDetails);
        panelMainDetails.setLayout(panelMainDetailsLayout);
        panelMainDetailsLayout.setHorizontalGroup(
            panelMainDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelMainDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVcName)
                    .addComponent(cmbVcStatus, 0, 342, Short.MAX_VALUE)
                    .addComponent(dtVcClosingTime, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(dtVcOpeningTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinVcCapacity))
                .addGap(16, 16, 16))
        );

        panelMainDetailsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbVcStatus, dtVcClosingTime, dtVcOpeningTime, spinVcCapacity, txtVcName});

        panelMainDetailsLayout.setVerticalGroup(
            panelMainDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainDetailsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelMainDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVcName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelMainDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtVcOpeningTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelMainDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtVcClosingTime, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelMainDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spinVcCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMainDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVcStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelMainDetailsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbVcStatus, dtVcClosingTime, dtVcOpeningTime, spinVcCapacity, txtVcName});

        panelTabbedVc.addTab("Main Details", panelMainDetails);

        cmbVcState.setMaximumRowCount(10);
        cmbVcState.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtVcAddr1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel6.setLabelFor(txtVcAddr2);
        jLabel6.setText("Address Line 2 :");
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel8.setLabelFor(cmbVcState);
        jLabel8.setText("State :");
        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel9.setLabelFor(txtVcAddr1);
        jLabel9.setText("Address Line 1 :");
        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtVcAddr2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        panelLocation.setLayer(cmbVcState, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelLocation.setLayer(txtVcAddr1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelLocation.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelLocation.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelLocation.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelLocation.setLayer(txtVcAddr2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLocationLayout = new javax.swing.GroupLayout(panelLocation);
        panelLocation.setLayout(panelLocationLayout);
        panelLocationLayout.setHorizontalGroup(
            panelLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLocationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtVcAddr1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(txtVcAddr2))
                    .addComponent(cmbVcState, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLocationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbVcState, txtVcAddr1, txtVcAddr2});

        panelLocationLayout.setVerticalGroup(
            panelLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLocationLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVcAddr1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(panelLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVcAddr2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVcState, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        panelLocationLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbVcState, txtVcAddr1, txtVcAddr2});

        panelTabbedVc.addTab("Location", panelLocation);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        panelVaccineChart.addTab("Chart", jPanel1);

        tblVcSupply.setModel(Vaccination_Centre.getVcSupplyTableModel(id, null));
        tblVcSupply.setRowHeight(30);
        jScrollPane1.setViewportView(tblVcSupply);

        panelVaccineChart.addTab("Table", jScrollPane1);

        btnVcSupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyVaccination/Images/Icons/supply_48.png"))); // NOI18N
        btnVcSupply.setText("Resupply");
        btnVcSupply.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnVcSupply.setIconTextGap(20);
        btnVcSupply.setPreferredSize(new java.awt.Dimension(111, 30));
        btnVcSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVcSupplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSupplyLayout = new javax.swing.GroupLayout(panelSupply);
        panelSupply.setLayout(panelSupplyLayout);
        panelSupplyLayout.setHorizontalGroup(
            panelSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSupplyLayout.createSequentialGroup()
                .addGroup(panelSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSupplyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelVaccineChart, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSupplyLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnVcSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelSupplyLayout.setVerticalGroup(
            panelSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSupplyLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelVaccineChart, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnVcSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panelTabbedVc.addTab("Vaccine Supply", panelSupply);

        getContentPane().add(panelTabbedVc, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 78, -1, -1));

        lblViewProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewProfile.setText("View Profile");
        lblViewProfile.setBackground(new java.awt.Color(204, 153, 255));
        lblViewProfile.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblViewProfile.setOpaque(true);
        lblViewProfile.setToolTipText("");
        lblViewProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewProfileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewProfileMousePressed(evt);
            }
        });
        getContentPane().add(lblViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 150, 40));

        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("Log Out");
        lblLogout.setBackground(new java.awt.Color(204, 153, 255));
        lblLogout.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblLogout.setOpaque(true);
        lblLogout.setToolTipText("");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLogoutMousePressed(evt);
            }
        });
        getContentPane().add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 150, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        int decision = JOptionPane.showConfirmDialog(this, "Warning, no unsaved changes will be saved!", "Cancel Vaccination Centre Registration", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

        // Return to Manage Vaccination Centre page
        if (decision == JOptionPane.OK_OPTION) {
            Personnel_Home home = new Personnel_Home(userId);
            home.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnVcSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVcSaveActionPerformed
        // Data Validation


        //Location Data
        String vcState = cmbVcState.getModel().getSelectedItem().toString();
        Location vcLocation = new Location(txtVcAddr1.getText(), txtVcAddr2.getText(), vcState);

        if (txtVcAddr1.getText().length() == 0 || txtVcAddr1.getText() == null) {

            panelTabbedVc.setSelectedIndex(1);
            return;
        }

        //Empty fields
        if (txtVcAddr1.getText().isBlank() || txtVcName.getText().isBlank() || dtVcOpeningTime.getTime() == null || dtVcClosingTime.getTime() == null) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Vaccination Centre", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
          //Opening after closing hours
        if (dtVcOpeningTime.getTime().isAfter(dtVcClosingTime.getTime())) {
            JOptionPane.showMessageDialog(this, "Invalid opening and closing hours!", "Vaccination Centre", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Set values
        vc.setClosingTime(dtVcClosingTime.getTime());
        vc.setOpeningTime(dtVcOpeningTime.getTime());
        vc.setName(txtVcName.getText());
        vc.setStatus(cmbVcStatus.getItemAt(cmbVcStatus.getSelectedIndex()));
        vc.setLocation(vcLocation);
        vc.setCapacity((Integer) spinVcCapacity.getValue());

        boolean success;
        String message = "";

        success = Vaccination_Centre.updateCentre(vc);

        if (id != "") {
            //Edit
            message = "Failed to update record for " + txtVcName.getText() + "!";
        } else {
            //New
            message = "Failed to register new vaccination centre!";
        }

        //Verify success of registration
        if (!success) {
            JOptionPane.showMessageDialog(this, message, "Vaccination Centre", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Personnel_ManageVaccinationCentre vcHome = new Personnel_ManageVaccinationCentre(userId);
        vcHome.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnVcSaveActionPerformed

    private void btnVcCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVcCancelActionPerformed

        //Check if user is certain
        int decision = JOptionPane.showConfirmDialog(this, "Warning, no unsaved changes will be saved!", "Cancel Vaccination Centre Registration", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

        // Return to Manage Vaccination Centre page
        if (decision == JOptionPane.OK_OPTION) {

            this.setVisible(false);
            this.dispose();
            Personnel_ManageVaccinationCentre vc = new Personnel_ManageVaccinationCentre(userId);
            vc.setVisible(true);
        }
    }//GEN-LAST:event_btnVcCancelActionPerformed

    private void btnVcSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVcSupplyActionPerformed
        // TODO add your handling code here:
        diaResupply.setLocationRelativeTo(this);
        diaResupply.setVisible(true);
    }//GEN-LAST:event_btnVcSupplyActionPerformed

    private void btnResupplyCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResupplyCancelActionPerformed

        //Check if user is certain
        int decision = JOptionPane.showConfirmDialog(diaResupply, "Warning, no unsaved changes will be saved!", "Cancel Vaccination Centre Resupply", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

        // Close the popup window
        if (decision == JOptionPane.OK_OPTION) {

            diaResupply.setVisible(false);
            diaResupply.dispose();
        }
    }//GEN-LAST:event_btnResupplyCancelActionPerformed

    private void btnResupplySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResupplySaveActionPerformed
        // Add vaccine supply

        String vaccineBrand = cmbResupplyVaccine.getModel().getSelectedItem().toString();
        for (int i = 1; i <= (int) spinResupply.getValue(); i++) {
            Vaccine newSupply = Vaccine.generateVaccine(vaccineBrand);
            vc.resupply(new Stock(newSupply));
        }

        spinResupply.setValue(1);

        //Close the window
        diaResupply.setVisible(false);
        diaResupply.dispose();

        //Regenerate the chart
        JFreeChart barChart = ChartFactory.createBarChart(
                txtVcName.getText() + " Supply",
                "Vaccines",
                "Quantity",
                vc.supplyDataset(),
                PlotOrientation.VERTICAL,
                true, true, false);

        ChartPanel chartPanel = new ChartPanel(barChart);
        panelVaccineChart.setComponentAt(0, chartPanel);

        //Reload the table
        tblVcSupply.setModel(Vaccination_Centre.getVcSupplyTableModel("", vc));
    }//GEN-LAST:event_btnResupplySaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(userId.equals("")){
            JOptionPane.showMessageDialog(null, "Please login into the system.", "Error", JOptionPane.ERROR_MESSAGE);
            Login login = new Login();
            login.setVisible(true);
            this.setVisible(false);
        }        

        //Generate supply chart
        String chartTitle = (vc.getName() == null) ? "Vaccination Centre" : vc.getName();
        CategoryDataset ds = (id != "") ? vc.supplyDataset() : new DefaultCategoryDataset();

        JFreeChart barChart = ChartFactory.createBarChart(
                chartTitle + " Supply",
                "Vaccines",
                "Quantity",
                ds,
                PlotOrientation.VERTICAL,
                true, true, false);

        ChartPanel chartPanel = new ChartPanel(barChart);
        panelVaccineChart.setComponentAt(0, chartPanel);
    }//GEN-LAST:event_formWindowOpened

    private void lblViewProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewProfileMouseEntered
        lblViewProfile.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Font font = lblViewProfile.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        lblViewProfile.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_lblViewProfileMouseEntered

    private void lblViewProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewProfileMouseExited
        Font font = lblViewProfile.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        lblViewProfile.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_lblViewProfileMouseExited

    private void lblViewProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewProfileMousePressed

        Personnel_ViewProfile viewProfile = new Personnel_ViewProfile(userId);
        viewProfile.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblViewProfileMousePressed

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Font font = lblLogout.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        lblLogout.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        Font font = lblLogout.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        lblLogout.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMousePressed
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblLogoutMousePressed

    private void lblUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseEntered
        lblUsername.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        Font font = lblUsername.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        lblUsername.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_lblUsernameMouseEntered

    private void lblUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMouseExited
        Font font = lblUsername.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        lblUsername.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_lblUsernameMouseExited

    private void lblUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMousePressed
        if (lblLogout.isVisible()) {
            lblViewProfile.setVisible(false);
            lblLogout.setVisible(false);
        } else {
            lblViewProfile.setVisible(true);
            lblLogout.setVisible(true);
        }
    }//GEN-LAST:event_lblUsernameMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personnel_VaccinationCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personnel_VaccinationCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personnel_VaccinationCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personnel_VaccinationCentreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personnel_VaccinationCentreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnResupplyCancel;
    private javax.swing.JButton btnResupplySave;
    private javax.swing.JButton btnVcCancel;
    private javax.swing.JButton btnVcSave;
    private javax.swing.JButton btnVcSupply;
    private javax.swing.JComboBox<String> cmbResupplyVaccine;
    private javax.swing.JComboBox<String> cmbVcState;
    private javax.swing.JComboBox<String> cmbVcStatus;
    private javax.swing.JDialog diaResupply;
    private com.github.lgooddatepicker.components.TimePicker dtVcClosingTime;
    private com.github.lgooddatepicker.components.TimePicker dtVcOpeningTime;
    private javax.swing.JPanel homePersonnelHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblViewProfile;
    private javax.swing.JLayeredPane panelLocation;
    private javax.swing.JLayeredPane panelMainDetails;
    private javax.swing.JPanel panelSupply;
    private javax.swing.JTabbedPane panelTabbedVc;
    private javax.swing.JTabbedPane panelVaccineChart;
    private javax.swing.JSpinner spinResupply;
    private javax.swing.JSpinner spinVcCapacity;
    private javax.swing.JTable tblVcSupply;
    private javax.swing.JTextField txtVcAddr1;
    private javax.swing.JTextField txtVcAddr2;
    private javax.swing.JTextField txtVcName;
    // End of variables declaration//GEN-END:variables
}
